// Step D.7 — the error classes used across the whole app, split out into a
// leaf module with no imports of its own.
//
// WHY THIS FILE EXISTS: js/auth.js needs NetworkError (a failed sign-in/
// refresh fetch is a network failure, same shape as an api.js network
// failure); js/api.js needs getAuth() from js/auth.js (to attach a session
// token and retry a 401). If the error classes stayed in api.js, importing
// auth.js from api.js and NetworkError from api.js in auth.js would be an
// import cycle. Putting the classes in a dependency-free leaf module both
// modules can import solves that without either depending on the other.
//
// js/api.js re-exports everything below by name so every existing import
// path (`import { ApiError } from './api.js'`, etc.) keeps working, and so
// `instanceof` checks keep working — these are the exact same class objects,
// not lookalikes.

export class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
    this.code = 'VALIDATION';
    this.retryable = false;
  }
}

export class NetworkError extends Error {
  constructor(message, cause) {
    super(message);
    this.name = 'NetworkError';
    this.code = 'NETWORK';
    this.retryable = true;
    this.cause = cause;
  }
}

export class ApiError extends Error {
  constructor({ status, method, url, body }) {
    const pgMessage = body && typeof body === 'object' ? body.message : null;
    const message = pgMessage
      ? `HTTP ${status}: ${pgMessage}`
      : `HTTP ${status}`;
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = (body && typeof body === 'object' && body.code) || null;
    this.details = (body && typeof body === 'object' && body.details) || null;
    this.hint = (body && typeof body === 'object' && body.hint) || null;
    this.body = body;
    this.method = method;
    this.url = url;
    this.retryable = status >= 500 || status === 408 || status === 429;
  }
}

// Step D.7 — signalled by js/auth.js for every sign-in/refresh/session
// failure. `reason` is what callers branch on (js/views/signin.js picks a
// user-facing message from it; js/store.js's isRetryable() decides whether
// a queued write survives).
//
// `retryable` matters specifically for the outbox (js/store.js): a write
// that failed because the session lapsed ('session_expired') or was never
// there ('signed_out') must stay queued so it is sent after the next
// sign-in — dropping it would silently lose a log. A wrong password on the
// sign-in form ('invalid_credentials') can never succeed by itself, so it
// is not retryable; nothing in the outbox is generated by a sign-in attempt
// anyway, but the flag stays consistent with every other error class here.
export class AuthError extends Error {
  constructor(message, { reason, status = null, body = null } = {}) {
    super(message);
    this.name = 'AuthError';
    this.code = 'AUTH';
    this.reason = reason;
    this.status = status;
    this.body = body;
    this.retryable = reason === 'session_expired' || reason === 'signed_out' || reason === 'server';
  }
}

export function isRetryable(err) {
  return !!(err && err.retryable === true);
}
