-- 0008_restorable_identity.sql
--
-- Step D.3, 2026-08-25. Makes the database restorable from a backup.
--
-- THE PROBLEM, found by actually trying to restore rather than by reading:
-- trackables.id and entries.id were GENERATED ALWAYS AS IDENTITY. Postgres
-- rejects an INSERT that supplies an explicit value for such a column unless
-- the statement says OVERRIDING SYSTEM VALUE — and PostgREST has no way to
-- emit that. So scripts/restore.mjs could not put a row back with its
-- original id, and any FK relationship in the dump (entries.trackable_id ->
-- trackables.id) would have been broken by re-assignment.
--
-- The backup would have looked perfectly healthy and been unusable at
-- exactly the moment it was needed. This is why Step D.3 requires the
-- restore to be executed, not just written.
--
-- THE FIX: GENERATED BY DEFAULT AS IDENTITY. Identical behaviour when the
-- client omits `id` (the app always does), but an explicit id is now
-- accepted. This is the normal choice for any table that must survive a
-- dump/restore cycle.
--
-- THE SEQUENCE HAZARD THAT COMES WITH IT: restoring explicit ids does not
-- advance the identity sequence, so the next app insert would reuse an id
-- that already exists and fail on the primary key. Anyone who has restored a
-- Postgres dump has hit this. daily_resync_identity() below fixes it, and
-- scripts/restore.mjs calls it as its last step so it cannot be forgotten.
--
-- app_settings.id is deliberately NOT an identity column (it is a hardcoded
-- singleton with `check (id = 1)`), so it needs neither change.

alter table public.trackables alter column id set generated by default;
alter table public.entries    alter column id set generated by default;

-- Re-points each identity sequence just past the largest id present, so the
-- next generated id cannot collide with a restored row. Safe to run any time,
-- including when a table is empty (setval falls back to 1 with is_called
-- false, so the next value is 1).
--
-- search_path is pinned to '' and every name is schema-qualified: an
-- unpinned search_path on a function is a standing privilege-escalation
-- footgun and Supabase's own advisors flag it.
create or replace function public.daily_resync_identity()
returns table (table_name text, next_id bigint)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  t text;
  max_id bigint;
begin
  foreach t in array array['trackables', 'entries'] loop
    execute format('select coalesce(max(id), 0) from public.%I', t) into max_id;
    perform setval(
      pg_get_serial_sequence(format('public.%I', t), 'id'),
      greatest(max_id, 1),
      max_id > 0
    );
    table_name := t;
    next_id := max_id + 1;
    return next;
  end loop;
end;
$$;

comment on function public.daily_resync_identity() is
  'Re-points trackables/entries identity sequences past the largest existing '
  'id. Called by scripts/restore.mjs after a restore, because restoring '
  'explicit ids does not advance the sequence. See migration 0008.';

-- NOTE FOR STEP D.7 (RLS hardening): this function is currently executable by
-- PUBLIC, which matches the wide-open policies on every table today. It only
-- resyncs sequences and leaks nothing, but revoke it from anon along with the
-- rest of the tightening rather than leaving it as the one thing still open.
